### ISSUE TITLE
Use TypeReference instead of Types directly when referring to types

### ISSUE THREAD

**Issue by panyam** [panyam/onering#14]
Currently types are directly pointed to.   This means that type objects are unique and cannot hold any context specific information.

For instance in a Record, fields are just type reference with a reference back to the parent instead of being seperated out into types and the field data.

Similarly when creating a signature having a type reference which holds a type + context specific data is more valuable than just a type (eg in doing late resolution of type names instead of having to generate ugly type names)

**Comment by panyam** [comment]
Done and looks bloody awesome if I may add!

**Comment by cheftako** [comment]
Yay!
